version: '3.9'

services:

  mongodb:
    image: mongo:5.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - secure-network
    volumes:
      - /app/hdp/mongo/data:/data/db 
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookdb --quiet

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - secure-network
    depends_on:
      - mongodb
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command: start-dev
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
   


networks:
    secure-network: